### ISSUE TITLE
Users.js / photos.js

### ISSUE THREAD

**Issue by janepark7** [justloffredo/photomatic_project#1]
Hey guys, 

Under `users.js`, it's picking up an error that states "Photos" has been declared. Then when viewing `photos.js`, mimeType is giving an error, which is causing my terminal to crash. Were you able to run this in the terminal?

**Comment by justloffredo** [comment]
Ok. So, I started to go through some of the template and picked up on some of the errors. In doing so, I also re-structured it a bit to have multiple routes based on users and photos. In addition, I've added a few more of the modules we've been using in class lately.
