### ISSUE TITLE
(API user auth)

### ISSUE THREAD

**Issue by justloffredo** [justloffredo/photomatic_project#7]
Hey Jane and Dave, 

I just updated the user authentication for api implementation..  If you could check it out to hopefully merge to master and move on to the next aspect. I changed a little bit as far as routes are concerned but nothing too hairy, and I don't believe it should affect anything you might have been working on.

**Comment by wbobeirne** [comment]
Hey Justin, this looks like it should be a pull request, and not an issue. There's no code associated with this issue, and nothing to merge.
